body:
  - type: textarea
    attributes:
      label: Goals
      description: Short list of what the feature request aims to address?
      value: |
        1.
        2.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Background
      description: Discuss prior art, why do you think this feature is needed? Are there current alternatives?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation
      description: How should this feature be implemented?
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Proposal
      options:
        label: I want to contribute implementing this feature
    validations:
      required: false
